// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PubsubPermission is the golang structure for table pubsub_permission.
type PubsubPermission struct {
	Id        int         `json:"id"        description:""`
	Topic     string      `json:"topic"     description:"订阅的主题名:AppMMID+topic"`
	Type      int         `json:"type"      description:"权限类型: 0:无认证，1:acl，2:基于密码，3:基于角色，4:etc"`
	Publisher string      `json:"publisher" description:"创建者,netDomain"`
	CreatedAt *gtime.Time `json:"createdAt" description:"Created Time"`
	UpdateAt  *gtime.Time `json:"updateAt"  description:"Updated Time"`
}
