// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/BioforestChain/dweb-browser-proxy/app/pubsub/logic/pubsub_permission"
)
