// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================
package logic

import (
	_ "proxyServer/internal/logic/auth"
	_ "proxyServer/internal/logic/middleware"
	_ "proxyServer/internal/logic/user"
)
