// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

type PubsubPermissionCreateInput struct {
	Id    int64
	Topic string //订阅的主题名
	Type  uint32 //权限类型: 0:无认证，1:acl，2:基于密码，3:基于角色，4:etc
	//Publisher string   //创建者，（若chat场景是群主）
	NetDomainNames string //acl中被授权的netDomain
	XDwebHostMMID  string //header
}
