// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/BioforestChain/dweb-browser-proxy/app/offline_storage/logic/offline_msg"
)
