// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// App is the golang structure of table app for DAO operations like Where/Data.
type App struct {
	g.Meta         `orm:"table:app, do:true"`
	Id             interface{} //
	UserId         interface{} // 用户id
	DeviceId       interface{} // 设备id
	Name           interface{} // 名称
	Identification interface{} // app唯一标识
	Remark         interface{} // 备注信息
	Timestamp      interface{} // 时间戳
	CreatedAt      *gtime.Time // Created Time
	UpdateAt       *gtime.Time // Updated Time
	DeletedAt      *gtime.Time // Deleted Time
	CumReqNum      interface{} // 累计被请求次数
	IsInstall      interface{} // 是否安装：1安装0（未安装）卸载
}
