// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// App is the golang structure of table app for DAO operations like Where/Data.
//type App struct {
//	g.Meta    `orm:"table:app, do:true"`
//	Id        interface{} //
//	UserId    interface{} // 用户id
//	Name      interface{} // 名称
//	Domain    interface{} // 域名
//	Remark    interface{} // 备注信息
//	Timestamp interface{} // 时间戳
//	CreatedAt *gtime.Time // Created Time
//	UpdateAt  *gtime.Time // Updated Time
//	DeletedAt *gtime.Time // Deleted Time
//}

type App struct {
	g.Meta         `orm:"table:app, do:true"`
	Id             interface{} `json:"id"`
	UserId         interface{} `json:"user_id"`              // 用户id
	DeviceId       interface{} `json:"device_id"`            // 设备id
	Name           interface{} `json:"name"`                 // 名称
	Identification interface{} `json:"identification"`       // app唯一标识
	Domain         interface{} `json:"domain"`               // 域名
	Remark         interface{} `json:"remark,omitempty"`     // 备注信息
	Timestamp      interface{} `json:"timestamp"`            // 时间戳
	CreatedAt      *gtime.Time `json:"created_at,omitempty"` // Created Time
	UpdateAt       *gtime.Time `json:"update_at,omitempty"`  // Updated Time
	DeletedAt      *gtime.Time `json:"deleted_at,omitempty"` // Deleted Time
}
