// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Net is the golang structure of table net for DAO operations like Where/Data.
type Net struct {
	g.Meta           `orm:"table:net, do:true"`
	Id               interface{} `json:"id"`                   //
	NetId            interface{} `json:"net_id"`               // 网络模块id
	ServerAddr       interface{} `json:"server_addr"`          // 服务地址
	BroadcastAddress interface{} `json:"broadcast_address"`    // 广播地址
	Remark           interface{} `json:"remark"`               // 备注信息
	Timestamp        interface{} `json:"timestamp"`            // 时间戳
	Port             interface{} `json:"port"`                 // 端口
	PublicKey        interface{} `json:"public_key"`           // rsa公钥
	PublicKeyMd5     interface{} `json:"public_key_md5"`       // rsa公钥
	IsOnline         interface{} `json:"is_online"`            // 上线：1上线，0下线
	CreatedAt        *gtime.Time `json:"created_at"`           // Created Time
	UpdateAt         *gtime.Time `json:"update_at"`            // Updated Time
	DeletedAt        *gtime.Time `json:"deleted_at,omitempty"` // Deleted Time
}
