// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Net is the golang structure of table net for DAO operations like Where/Data.
type Net struct {
	g.Meta    `orm:"table:net, do:true"`
	Id        interface{} //
	NetId     interface{} // 网络模块id
	Domain    interface{} // 域名
	Remark    interface{} // 备注信息
	Timestamp interface{} // 时间戳
	InOnline  interface{} // 上线：1上线，0下线
	CreatedAt *gtime.Time // Created Time
	UpdateAt  *gtime.Time // Updated Time
	DeletedAt *gtime.Time // Deleted Time
}
