// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ProxyServerUser is the golang structure of table user for DAO operations like Where/Data.
type ProxyServerUser struct {
	g.Meta         `orm:"table:user, do:true"`
	Id             interface{} //
	Name           interface{} // 用户名
	Identification interface{} // 设备标识
	Domain         interface{} // 域名
	PublicKey      interface{} // 公钥
	Timestamp      interface{} // 时间戳
	Remark         interface{} // 备注信息
	CreatedAt      *gtime.Time // Created Time
	UpdateAt       *gtime.Time // Updated Time
	DeletedAt      *gtime.Time // Deleted Time
}
