// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ProxyServerUser is the golang structure of table user for DAO operations like Where/Data.
type ProxyServerUser struct {
	g.Meta         `orm:"table:user, do:true"`
	Id             interface{} //
	Name           interface{} `gorm:"column:name" db:"name" json:"name" form:"name"` // 用户名
	Identification interface{} `gorm:"column:identification" db:"identification" json:"identification" form:"identification"` // 设备标识
	Domain         interface{} `gorm:"column:domain" db:"domain" json:"domain" form:"domain"` // 域名
	PublicKey      interface{} `gorm:"column:public_key" db:"public_key" json:"public_key" form:"public_key"` // 公钥
	Timestamp      interface{} `gorm:"column:timestamp" db:"timestamp" json:"timestamp" form:"timestamp"` // 时间戳
	Remark         interface{} `gorm:"column:remark" db:"remark" json:"remark" form:"remark"` // 备注信息
	CreatedAt      *gtime.Time `gorm:"column:created_at" db:"created_at" json:"created_at" form:"created_at"` // Created Time
	UpdateAt       *gtime.Time `gorm:"column:update_at" db:"update_at" json:"update_at" form:"update_at"` // Updated Time
	DeletedAt      *gtime.Time `gorm:"column:deleted_at" db:"deleted_at" json:"deleted_at" form:"deleted_at"` // Deleted Time
}
