// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PubsubPermission is the golang structure of table pubsub_permission for DAO operations like Where/Data.
type PubsubPermission struct {
	g.Meta    `orm:"table:pubsub_permission, do:true"`
	Id        interface{} //
	Topic     interface{} // 订阅的主题名:AppMMID+topic
	Type      interface{} // 权限类型: 0:无认证，1:acl，2:基于密码，3:基于角色，4:etc
	Publisher interface{} // 创建者,netDomain
	CreatedAt *gtime.Time // Created Time
	UpdateAt  *gtime.Time // Updated Time
}
