// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FrpcUserDao is the data access object for table frpc_user.
type FrpcUserDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns FrpcUserColumns // columns contains all the column names of Table for convenient usage.
}

// FrpcUserColumns defines and stores column names for table frpc_user.
type FrpcUserColumns struct {
	Id             string //
	Name           string // 用户名
	Identification string // 设备标识
	Remark         string // 备注信息
	CreatedAt      string // Created Time
	UpdateAt       string // Updated Time
	DeletedAt      string // Deleted Time
}

// frpcUserColumns holds the columns for table frpc_user.
var frpcUserColumns = FrpcUserColumns{
	Id:             "id",
	Name:           "name",
	Identification: "identification",
	Remark:         "remark",
	CreatedAt:      "created_at",
	UpdateAt:       "update_at",
	DeletedAt:      "deleted_at",
}

// NewFrpcUserDao creates and returns a new DAO object for table data access.
func NewFrpcUserDao() *FrpcUserDao {
	return &FrpcUserDao{
		group:   "default",
		table:   "frpc_user",
		columns: frpcUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FrpcUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FrpcUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *FrpcUserDao) Columns() FrpcUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *FrpcUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FrpcUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FrpcUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
