// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PubsubPermissionDao is the data access object for table pubsub_permission.
type PubsubPermissionDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns PubsubPermissionColumns // columns contains all the column names of Table for convenient usage.
}

// PubsubPermissionColumns defines and stores column names for table pubsub_permission.
type PubsubPermissionColumns struct {
	Id        string //
	Topic     string // 订阅的主题名:AppMMID+topic
	Type      string // 权限类型: 0:无认证，1:acl，2:基于密码，3:基于角色，4:etc
	Publisher string // 创建者,netDomain
	CreatedAt string // Created Time
	UpdateAt  string // Updated Time
}

// pubsubPermissionColumns holds the columns for table pubsub_permission.
var pubsubPermissionColumns = PubsubPermissionColumns{
	Id:        "id",
	Topic:     "topic",
	Type:      "type",
	Publisher: "publisher",
	CreatedAt: "created_at",
	UpdateAt:  "update_at",
}

// NewPubsubPermissionDao creates and returns a new DAO object for table data access.
func NewPubsubPermissionDao() *PubsubPermissionDao {
	return &PubsubPermissionDao{
		group:   "default",
		table:   "pubsub_permission",
		columns: pubsubPermissionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PubsubPermissionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PubsubPermissionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PubsubPermissionDao) Columns() PubsubPermissionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PubsubPermissionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PubsubPermissionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PubsubPermissionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
