// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ProxyServerUserDao is the data access object for table user.
type ProxyServerUserDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns ProxyServerUserColumns // columns contains all the column names of Table for convenient usage.
}

// ProxyServerUserColumns defines and stores column names for table user.
type ProxyServerUserColumns struct {
	Id             string //
	Name           string // 用户名
	Domain         string // 域名
	Identification string // 设备标识
	Remark         string // 备注信息
	CreatedAt      string // Created Time
	UpdateAt       string // Updated Time
	DeletedAt      string // Deleted Time
}

// proxyServerUserColumns holds the columns for table user.
var proxyServerUserColumns = ProxyServerUserColumns{
	Id:             "id",
	Name:           "name",
	Domain:         "domain", // 域名
	Identification: "identification",
	Remark:         "remark",
	CreatedAt:      "created_at",
	UpdateAt:       "update_at",
	DeletedAt:      "deleted_at",
}

// NewProxyServerUserDao creates and returns a new DAO object for table data access.
func NewProxyServerUserDao() *ProxyServerUserDao {
	return &ProxyServerUserDao{
		group:   "default",
		table:   "user",
		columns: proxyServerUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ProxyServerUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ProxyServerUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ProxyServerUserDao) Columns() ProxyServerUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ProxyServerUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ProxyServerUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ProxyServerUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

