// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	v1 "proxyServer/api/client/v1"
	"proxyServer/internal/model"
)

type (
	IApp interface {
		CreateAppModule(ctx context.Context, in model.AppModuleCreateInput) (entity *v1.ClientAppModuleRegRes, err error)
		CreateAppInfo(ctx context.Context, in model.AppModuleInfoCreateInput) (err error)
		DelAppById(ctx context.Context, in model.AppModuleDelInput) (err error)
		GetAppModuleList(ctx context.Context, in model.AppModuleListQueryInput) (entities []*v1.ClientAppModuleDetailRes, total int, err error)
	}
)

var (
	localApp IApp
)

func App() IApp {
	if localApp == nil {
		panic("implement not found for interface IApp, forgot register?")
	}
	return localApp
}

func RegisterApp(i IApp) {
	localApp = i
}
