// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	v1 "proxyServer/api/client/v1"
	"proxyServer/internal/model/entity"
	//"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IMiddleware interface {
		GenToken(userID uint32, deviceIdentification string) (string, string, int64, error)
		ParseToken(tokenString string) (*entity.MyClaims, error)
		RefreshToken(accessToken, refreshToken string) (*v1.ClientUserRefreshTokenRes, error)
		//ResponseHandler(r *ghttp.Request)
	}
)

var (
	localMiddleware IMiddleware
)

func Middleware() IMiddleware {
	if localMiddleware == nil {
		panic("implement not found for interface IMiddleware, forgot register?")
	}
	return localMiddleware
}

func RegisterMiddleware(i IMiddleware) {
	localMiddleware = i
}
