// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	v1 "proxyServer/api/client/v1"
	"proxyServer/internal/model"
)

type (
	INet interface {
		CreateNetModule(ctx context.Context, in model.NetModuleCreateInputReq) (entity *v1.ClientNetModuleRegRes, err error)
		IsDomainExist(ctx context.Context, Domain string) (bool, error)
	}
)

var (
	localNet INet
)

func Net() INet {
	if localNet == nil {
		panic("implement not found for interface INet, forgot register?")
	}
	return localNet
}

func RegisterNet(i INet) {
	localNet = i
}
