// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	v1 "github.com/BioforestChain/dweb-browser-proxy/api/client/v1"
	"github.com/BioforestChain/dweb-browser-proxy/internal/model"
)

type (
	INet interface {
		CreateNetModule(ctx context.Context, in model.NetModuleCreateInput) (entity *v1.ClientNetModuleDetailRes, err error)
		GetNetModuleDetailById(ctx context.Context, in model.NetModuleDetailInput) (entity *v1.ClientNetModuleDetailRes, err error)
		GetNetModuleList(ctx context.Context, in model.NetModuleListQueryInput) (entities []*v1.ClientNetModuleDetailRes, total int, err error)
		IsServerAddrExist(ctx context.Context, serverAddr string) (bool, error)
		IsBroadcastAddressExist(ctx context.Context, broadcastAddress, publicKeyMd5 string) (bool, error)
	}
)

var (
	localNet INet
)

func Net() INet {
	if localNet == nil {
		panic("implement not found for interface INet, forgot register?")
	}
	return localNet
}

func RegisterNet(i INet) {
	localNet = i
}
