// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	v1 "github.com/BioforestChain/dweb-browser-proxy/api/offline_msg/v1"
	"github.com/BioforestChain/dweb-browser-proxy/internal/model"
)

type (
	IOfflineMsg interface {
		//DelOfflineMsgById(ctx context.Context, in model.OfflineMsgModuleDelInput) (err error)
		GetOfflineMsgList(ctx context.Context, in model.OfflineMsgListQueryInput) (entities []*v1.Res, total int, err error)
	}
)

var (
	localOfflineMsg IOfflineMsg
)

func OfflineMsg() IOfflineMsg {
	if localOfflineMsg == nil {
		panic("implement not found for interface IOfflineMsg, forgot register?")
	}
	return localOfflineMsg
}

func RegisterOfflineMsg(i IOfflineMsg) {
	localOfflineMsg = i
}
