// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	v1 "github.com/BioforestChain/dweb-browser-proxy/api/pubsub_permission/v1"
	"github.com/BioforestChain/dweb-browser-proxy/internal/model"
)

type (
	IPubsubPermission interface {
		CreatePubsubPermission(ctx context.Context, in model.PubsubPermissionCreateInput) (entity *v1.PubsubPermissionDetailRes, err error)
		IsPubsubPermissionTopicNameExist(ctx context.Context, Topic string) (bool, error)
	}
)

var (
	localPubsubPermission IPubsubPermission
)

func PubsubPermission() IPubsubPermission {
	if localPubsubPermission == nil {
		panic("implement not found for interface IPubsubPermission, forgot register?")
	}
	return localPubsubPermission
}

func RegisterPubsubPermission(i IPubsubPermission) {
	localPubsubPermission = i
}
