// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"proxyServer/internal/dao/internal"
)

// internalProxyServerUserDao is internal type for wrapping internal DAO implements.
type internalProxyServerUserDao = *internal.ProxyServerUserDao

// ProxyServerUserDao is the data access object for table user.
// You can define custom methods on it to extend its functionality as you wish.
type ProxyServerUserDao struct {
	internalProxyServerUserDao
}

var (
	// ProxyServerUser is globally public accessible object for table user operations.
	ProxyServerUser = ProxyServerUserDao{
		internal.NewProxyServerUserDao(),
	}
)

// Fill with you ideas below.
