// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"frpConfManagement/internal/dao/internal"
)

// internalFrpcUserDao is internal type for wrapping internal DAO implements.
type internalFrpcUserDao = *internal.FrpcUserDao

// frpcUserDao is the data access object for table frpc_user.
// You can define custom methods on it to extend its functionality as you wish.
type frpcUserDao struct {
	internalFrpcUserDao
}

var (
	// FrpcUser is globally public accessible object for table frpc_user operations.
	FrpcUser = frpcUserDao{
		internal.NewFrpcUserDao(),
	}
)

// Fill with you ideas below.
