// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/BioforestChain/dweb-browser-proxy/internal/dao/internal"
)

// internalPubsubUserAclDao is internal type for wrapping internal DAO implements.
type internalPubsubUserAclDao = *internal.PubsubUserAclDao

// pubsubUserAclDao is the data access object for table pubsub_user_acl.
// You can define custom methods on it to extend its functionality as you wish.
type pubsubUserAclDao struct {
	internalPubsubUserAclDao
}

var (
	// PubsubUserAcl is globally public accessible object for table pubsub_user_acl operations.
	PubsubUserAcl = pubsubUserAclDao{
		internal.NewPubsubUserAclDao(),
	}
)

// Fill with you ideas below.
