// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PubsubUserAclDao is the data access object for table pubsub_user_acl.
type PubsubUserAclDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns PubsubUserAclColumns // columns contains all the column names of Table for convenient usage.
}

// PubsubUserAclColumns defines and stores column names for table pubsub_user_acl.
type PubsubUserAclColumns struct {
	Id           string //
	PermissionId string // permission主键
	NetDomain    string // netDomain
	CreatedAt    string // Created Time
	UpdateAt     string // Updated Time
}

// pubsubUserAclColumns holds the columns for table pubsub_user_acl.
var pubsubUserAclColumns = PubsubUserAclColumns{
	Id:           "id",
	PermissionId: "permission_id",
	NetDomain:    "net_domain",
	CreatedAt:    "created_at",
	UpdateAt:     "update_at",
}

// NewPubsubUserAclDao creates and returns a new DAO object for table data access.
func NewPubsubUserAclDao() *PubsubUserAclDao {
	return &PubsubUserAclDao{
		group:   "default",
		table:   "pubsub_user_acl",
		columns: pubsubUserAclColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PubsubUserAclDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PubsubUserAclDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PubsubUserAclDao) Columns() PubsubUserAclColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PubsubUserAclDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PubsubUserAclDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PubsubUserAclDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
