// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FrpcUser is the golang structure for table frpc_user.
type FrpcUser struct {
	Id             int         `json:"id"             description:""`
	Name           string      `json:"name"           description:"用户名"`
	Identification string      `json:"identification" description:"设备标识"`
	Remark         string      `json:"remark"         description:"备注信息"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"Created Time"`
	UpdateAt       *gtime.Time `json:"updateAt"       description:"Updated Time"`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:"Deleted Time"`
}
