// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Net is the golang structure for table net.
type Net struct {
	Id        int64       `json:"id"        description:""`
	NetId     string      `json:"netId"     description:"网络模块id"`
	Domain    string      `json:"domain"    description:"域名"`
	Remark    string      `json:"remark"    description:"备注信息"`
	Timestamp int         `json:"timestamp" description:"时间戳"`
	InOnline  int         `json:"inOnline"  description:"上线：1上线，0下线"`
	CreatedAt *gtime.Time `json:"createdAt" description:"Created Time"`
	UpdateAt  *gtime.Time `json:"updateAt"  description:"Updated Time"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"Deleted Time"`
}
